-- MySQL Script generated by MySQL Workbench
-- Mon Apr  2 17:51:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`contact_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contact_info` (
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`phone`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`traffic_police`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`traffic_police` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `contact_info_phone` INT NOT NULL,
  PRIMARY KEY (`id`, `contact_info_phone`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_traffic_police_contact_info1_idx` (`contact_info_phone` ASC),
  CONSTRAINT `fk_traffic_police_contact_info1`
    FOREIGN KEY (`contact_info_phone`)
    REFERENCES `mydb`.`contact_info` (`phone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`police_officer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`police_officer` (
  `badge` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `rank` VARCHAR(45) NOT NULL,
  `traffic_police_id` INT NOT NULL,
  `chief_badge` INT NOT NULL,
  `police_officer_traffic_police_id` INT NOT NULL,
  PRIMARY KEY (`badge`, `traffic_police_id`),
  UNIQUE INDEX `badge_UNIQUE` (`badge` ASC),
  INDEX `fk_police_officer_traffic_police_idx` (`traffic_police_id` ASC),
  INDEX `fk_police_officer_police_officer1_idx` (`chief_badge` ASC, `police_officer_traffic_police_id` ASC),
  CONSTRAINT `fk_police_officer_traffic_police`
    FOREIGN KEY (`traffic_police_id`)
    REFERENCES `mydb`.`traffic_police` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chief`
    FOREIGN KEY (`chief_badge` , `police_officer_traffic_police_id`)
    REFERENCES `mydb`.`police_officer` (`badge` , `traffic_police_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`report` (
  `DOTA` INT NOT NULL,
  PRIMARY KEY (`DOTA`),
  UNIQUE INDEX `DOTA_UNIQUE` (`DOTA` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`coordinates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`coordinates` (
  `latitude` INT NOT NULL,
  `longitude` INT NOT NULL,
  PRIMARY KEY (`latitude`, `longitude`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`street_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`street_info` (
  `name` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `road_surface` VARCHAR(45) NOT NULL,
  `state_of_road_surface` VARCHAR(45) NOT NULL,
  `speed_limit` INT NOT NULL,
  PRIMARY KEY (`name`, `number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`accident`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accident` (
  `date_of_registration` DATE NOT NULL,
  `date_of_review` DATE NOT NULL,
  `description` TEXT NOT NULL,
  `redactor` INT NOT NULL,
  `chief` INT NOT NULL,
  `report_DOTA` INT NOT NULL,
  `traffic_police_id` INT NOT NULL,
  `traffic_police_contact_info_phone` INT NOT NULL,
  `coordinates_latitude` INT NOT NULL,
  `coordinates_longitude` INT NOT NULL,
  `street_info_name` VARCHAR(45) NOT NULL,
  `street_info_number` INT NOT NULL,
  PRIMARY KEY (`date_of_registration`, `date_of_review`, `report_DOTA`, `traffic_police_id`, `traffic_police_contact_info_phone`, `coordinates_latitude`, `coordinates_longitude`, `street_info_name`, `street_info_number`),
  INDEX `fk_redactor_idx` (`redactor` ASC),
  INDEX `fk_chief_idx` (`chief` ASC),
  INDEX `fk_accident_report1_idx` (`report_DOTA` ASC),
  INDEX `fk_accident_traffic_police1_idx` (`traffic_police_id` ASC, `traffic_police_contact_info_phone` ASC),
  INDEX `fk_accident_coordinates1_idx` (`coordinates_latitude` ASC, `coordinates_longitude` ASC),
  INDEX `fk_accident_street_info1_idx` (`street_info_name` ASC, `street_info_number` ASC),
  CONSTRAINT `fk_redactor`
    FOREIGN KEY (`redactor`)
    REFERENCES `mydb`.`police_officer` (`badge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chief`
    FOREIGN KEY (`chief`)
    REFERENCES `mydb`.`police_officer` (`badge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accident_report1`
    FOREIGN KEY (`report_DOTA`)
    REFERENCES `mydb`.`report` (`DOTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accident_traffic_police1`
    FOREIGN KEY (`traffic_police_id` , `traffic_police_contact_info_phone`)
    REFERENCES `mydb`.`traffic_police` (`id` , `contact_info_phone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accident_coordinates1`
    FOREIGN KEY (`coordinates_latitude` , `coordinates_longitude`)
    REFERENCES `mydb`.`coordinates` (`latitude` , `longitude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accident_street_info1`
    FOREIGN KEY (`street_info_name` , `street_info_number`)
    REFERENCES `mydb`.`street_info` (`name` , `number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commercial_firm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commercial_firm` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `parent_company` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_parent_company_idx` (`parent_company` ASC),
  CONSTRAINT `fk_parent_company`
    FOREIGN KEY (`parent_company`)
    REFERENCES `mydb`.`commercial_firm` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`risk_of_merchandise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`risk_of_merchandise` (
  `id` INT NOT NULL,
  `class` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`merchandise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`merchandise` (
  `id` INT NOT NULL,
  `weight` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `commercial_firm` INT NOT NULL,
  `risk_factor` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_commercial_firm_idx` (`commercial_firm` ASC),
  INDEX `fk_risk_factor_idx` (`risk_factor` ASC),
  CONSTRAINT `fk_commercial_firm`
    FOREIGN KEY (`commercial_firm`)
    REFERENCES `mydb`.`commercial_firm` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_risk_factor`
    FOREIGN KEY (`risk_factor`)
    REFERENCES `mydb`.`risk_of_merchandise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`insurance_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`insurance_company` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `parent_company` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_parent_company_idx` (`parent_company` ASC),
  CONSTRAINT `fk_parent_company`
    FOREIGN KEY (`parent_company`)
    REFERENCES `mydb`.`insurance_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ADT` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `AFM` INT NOT NULL,
  `AMKA` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `AFM_UNIQUE` (`AFM` ASC),
  UNIQUE INDEX `AMKA_UNIQUE` (`AMKA` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medical_procedure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medical_procedure` (
  `id` INT NOT NULL,
  `description` TEXT NOT NULL,
  `body_parts` VARCHAR(45) NOT NULL,
  `duration` INT NOT NULL,
  `result` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`catalog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`catalog` (
  `procedure_id` INT NOT NULL,
  PRIMARY KEY (`procedure_id`),
  UNIQUE INDEX `procedure_id_UNIQUE` (`procedure_id` ASC),
  CONSTRAINT `fk_procedure_id`
    FOREIGN KEY (`procedure_id`)
    REFERENCES `mydb`.`medical_procedure` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospital` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `catalog_procedure_id` INT NOT NULL,
  PRIMARY KEY (`id`, `catalog_procedure_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_hospital_catalog1_idx` (`catalog_procedure_id` ASC),
  CONSTRAINT `fk_hospital_catalog1`
    FOREIGN KEY (`catalog_procedure_id`)
    REFERENCES `mydb`.`catalog` (`procedure_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nature` INT NOT NULL,
  `age` INT NOT NULL,
  `ADT` INT NOT NULL,
  `hospital_id` INT NULL,
  `accident_date_of_registration` DATE NOT NULL,
  `accident_date_of_review` DATE NOT NULL,
  `accident_report_DOTA` INT NOT NULL,
  `accident_traffic_police_id` INT NOT NULL,
  `accident_traffic_police_contact_info_phone` INT NOT NULL,
  `accident_coordinates_latitude` INT NOT NULL,
  `accident_coordinates_longitude` INT NOT NULL,
  `accident_street_info_name` VARCHAR(45) NOT NULL,
  `accident_street_info_number` INT NOT NULL,
  PRIMARY KEY (`id`, `ADT`, `accident_report_DOTA`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nature_UNIQUE` (`nature` ASC),
  UNIQUE INDEX `ADT_UNIQUE` (`ADT` ASC),
  INDEX `fk_person_accident1_idx` (`accident_date_of_registration` ASC, `accident_date_of_review` ASC, `accident_report_DOTA` ASC, `accident_traffic_police_id` ASC, `accident_traffic_police_contact_info_phone` ASC, `accident_coordinates_latitude` ASC, `accident_coordinates_longitude` ASC, `accident_street_info_name` ASC, `accident_street_info_number` ASC),
  INDEX `fk_hospital_id_idx` (`hospital_id` ASC),
  CONSTRAINT `fk_ADT`
    FOREIGN KEY (`ADT`)
    REFERENCES `mydb`.`ADT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_accident1`
    FOREIGN KEY (`accident_date_of_registration` , `accident_date_of_review` , `accident_report_DOTA` , `accident_traffic_police_id` , `accident_traffic_police_contact_info_phone` , `accident_coordinates_latitude` , `accident_coordinates_longitude` , `accident_street_info_name` , `accident_street_info_number`)
    REFERENCES `mydb`.`accident` (`date_of_registration` , `date_of_review` , `report_DOTA` , `traffic_police_id` , `traffic_police_contact_info_phone` , `coordinates_latitude` , `coordinates_longitude` , `street_info_name` , `street_info_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospital_id`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `mydb`.`hospital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehicle_registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vehicle_registration` (
  `plate_number` INT NOT NULL,
  `frame_number` INT NOT NULL,
  `manufacturer` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `engine_ccm` INT NOT NULL,
  `release_year` INT NOT NULL,
  `owner` INT NOT NULL,
  PRIMARY KEY (`plate_number`, `frame_number`),
  UNIQUE INDEX `plate_number_UNIQUE` (`plate_number` ASC),
  UNIQUE INDEX `frame_number_UNIQUE` (`frame_number` ASC),
  INDEX `fk_owner_idx` (`owner` ASC),
  CONSTRAINT `fk_owner`
    FOREIGN KEY (`owner`)
    REFERENCES `mydb`.`person` (`ADT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vehicle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `estimated_collision_speed` INT NOT NULL,
  `passengers` INT NOT NULL,
  `insurance_company` INT NULL,
  `merchandise` INT NULL,
  `accident_date_of_registration` DATE NOT NULL,
  `accident_date_of_review` DATE NOT NULL,
  `accident_report_DOTA` INT NOT NULL,
  `accident_traffic_police_id` INT NOT NULL,
  `accident_traffic_police_contact_info_phone` INT NOT NULL,
  `accident_coordinates_latitude` INT NOT NULL,
  `accident_coordinates_longitude` INT NOT NULL,
  `accident_street_info_name` VARCHAR(45) NOT NULL,
  `accident_street_info_number` INT NOT NULL,
  `vehicle_registration_plate_number` INT NOT NULL,
  `vehicle_registration_frame_number` INT NOT NULL,
  PRIMARY KEY (`id`, `accident_date_of_registration`, `accident_date_of_review`, `accident_report_DOTA`, `accident_traffic_police_id`, `accident_traffic_police_contact_info_phone`, `accident_coordinates_latitude`, `accident_coordinates_longitude`, `accident_street_info_name`, `accident_street_info_number`, `vehicle_registration_plate_number`, `vehicle_registration_frame_number`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_merchandise_idx` (`merchandise` ASC),
  INDEX `fk_insurance_company_idx` (`insurance_company` ASC),
  INDEX `fk_vehicle_accident1_idx` (`accident_date_of_registration` ASC, `accident_date_of_review` ASC, `accident_report_DOTA` ASC, `accident_traffic_police_id` ASC, `accident_traffic_police_contact_info_phone` ASC, `accident_coordinates_latitude` ASC, `accident_coordinates_longitude` ASC, `accident_street_info_name` ASC, `accident_street_info_number` ASC),
  INDEX `fk_vehicle_vehicle_registration1_idx` (`vehicle_registration_plate_number` ASC, `vehicle_registration_frame_number` ASC),
  CONSTRAINT `fk_merchandise`
    FOREIGN KEY (`merchandise`)
    REFERENCES `mydb`.`merchandise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_insurance_company`
    FOREIGN KEY (`insurance_company`)
    REFERENCES `mydb`.`insurance_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_accident1`
    FOREIGN KEY (`accident_date_of_registration` , `accident_date_of_review` , `accident_report_DOTA` , `accident_traffic_police_id` , `accident_traffic_police_contact_info_phone` , `accident_coordinates_latitude` , `accident_coordinates_longitude` , `accident_street_info_name` , `accident_street_info_number`)
    REFERENCES `mydb`.`accident` (`date_of_registration` , `date_of_review` , `report_DOTA` , `traffic_police_id` , `traffic_police_contact_info_phone` , `coordinates_latitude` , `coordinates_longitude` , `street_info_name` , `street_info_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_vehicle_registration1`
    FOREIGN KEY (`vehicle_registration_plate_number` , `vehicle_registration_frame_number`)
    REFERENCES `mydb`.`vehicle_registration` (`plate_number` , `frame_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`driver` (
  `KOK` INT NOT NULL,
  UNIQUE INDEX `KOK_UNIQUE` (`KOK` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`license`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`license` (
  `id` INT NOT NULL,
  `ethnicity` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `date_issued` DATE NOT NULL,
  `ADT` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`passenger` (
  `vehicle_id` INT NOT NULL,
  `seat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`vehicle_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipment` (
  `seat_belt` INT NOT NULL,
  `airbag` TINYINT NULL,
  PRIMARY KEY (`seat_belt`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alcotest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alcotest` (
  `type` VARCHAR(45) NOT NULL,
  `time` TIME NOT NULL,
  `result` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`accident_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accident_report` (
  `date_of_report` DATE NOT NULL,
  `estimated_damage` INT NOT NULL,
  `estimated_compensation` INT NOT NULL,
  `DOTA` INT NOT NULL,
  `vehicle_registration` INT NOT NULL,
  `insurance_company_id` INT NOT NULL,
  INDEX `fk_report_DOTA_idx` (`DOTA` ASC),
  INDEX `fk_vehicle_registration_idx` (`vehicle_registration` ASC),
  PRIMARY KEY (`DOTA`, `insurance_company_id`),
  INDEX `fk_accident_report_insurance_company1_idx` (`insurance_company_id` ASC),
  CONSTRAINT `fk_report_DOTA`
    FOREIGN KEY (`DOTA`)
    REFERENCES `mydb`.`report` (`DOTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_registration`
    FOREIGN KEY (`vehicle_registration`)
    REFERENCES `mydb`.`vehicle_registration` (`plate_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accident_report_insurance_company1`
    FOREIGN KEY (`insurance_company_id`)
    REFERENCES `mydb`.`insurance_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctor` (
  `id` INT NOT NULL,
  `licence_id` INT NOT NULL,
  `specialisation` VARCHAR(45) NOT NULL,
  `hospital_id` INT NOT NULL,
  PRIMARY KEY (`id`, `hospital_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `licence_id_UNIQUE` (`licence_id` ASC),
  INDEX `fk_doctor_hospital1_idx` (`hospital_id` ASC),
  CONSTRAINT `fk_doctor_hospital1`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `mydb`.`hospital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`discharge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`discharge` (
  `day` VARCHAR(45) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admission` (
  `id` INT NOT NULL,
  `day` VARCHAR(45) NOT NULL,
  `time` TIME NOT NULL,
  `severity` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  `patient_id` INT NOT NULL,
  `patient_ADT` INT NOT NULL,
  `patient_DOTA` INT NOT NULL,
  `hospital_id` INT NOT NULL,
  `discharge_id` INT NOT NULL,
  PRIMARY KEY (`id`, `discharge_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_patient_idx` (`patient_id` ASC),
  INDEX `fk_patient_ADT_idx` (`patient_ADT` ASC),
  INDEX `fk_patient_DOTA_idx` (`patient_DOTA` ASC),
  INDEX `fk_hospital_id_idx` (`hospital_id` ASC),
  INDEX `fk_admission_discharge1_idx` (`discharge_id` ASC),
  CONSTRAINT `fk_patient_id`
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_ADT`
    FOREIGN KEY (`patient_ADT`)
    REFERENCES `mydb`.`person` (`ADT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_DOTA`
    FOREIGN KEY (`patient_DOTA`)
    REFERENCES `mydb`.`person` (`accident_report_DOTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospital_id`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `mydb`.`person` (`hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admission_discharge1`
    FOREIGN KEY (`discharge_id`)
    REFERENCES `mydb`.`discharge` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medical_procedure_has_doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medical_procedure_has_doctor` (
  `medical_procedure_id` INT NOT NULL,
  `doctor_id` INT NOT NULL,
  `doctor_hospital_id` INT NOT NULL,
  PRIMARY KEY (`medical_procedure_id`, `doctor_id`, `doctor_hospital_id`),
  INDEX `fk_medical_procedure_has_doctor_doctor1_idx` (`doctor_id` ASC, `doctor_hospital_id` ASC),
  INDEX `fk_medical_procedure_has_doctor_medical_procedure1_idx` (`medical_procedure_id` ASC),
  CONSTRAINT `fk_medical_procedure_has_doctor_medical_procedure1`
    FOREIGN KEY (`medical_procedure_id`)
    REFERENCES `mydb`.`medical_procedure` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medical_procedure_has_doctor_doctor1`
    FOREIGN KEY (`doctor_id` , `doctor_hospital_id`)
    REFERENCES `mydb`.`doctor` (`id` , `hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
